### ISSUE TITLE
What is the difference...

### ISSUE THREAD

**Issue by antrecu** [lion24/RTL8812au#4]
Hi,
Quick question, what is the difference between this driver and the ones provided by Ubuntu: rtl8812au-dkms ?

Thanks!

**Comment by lion24** [comment]
Hi,

I'm experiencing issue with the one coming from the ubuntu repository. I didn't do a lot of investigation why. This driver (from my repo) works well with my current kernel (4.4.0-43-generic). 

This driver is far from being perfect it does not well integrate with **iw** command due to some missing ioctl functions. I'm working on integrating those ioctl system calls into the driver.

Cheers.
